### PR TITLE
[i18n] Translatable Casper default theme

### PR DESCRIPTION
**Pull request by juan-g**
[i18n] Translatable Casper default theme

no issue

- (note: this Casper commit completes a Ghost commit with full translation of Ghost's frontend for site visitors: _"[i18n] Translatable Ghost's frontend: Themes, dates, pagination, subscribe forms"_)

- all 21 theme text strings included in translatable `{{t}}` handlebars helpers in Casper, the Ghost default theme which is the model for all Ghost themes
- easily readable original English text in templates, for very simple translation
- usage examples, in .hbs templates:
```
  {{t "mytheme" "Get the latest posts delivered right to your inbox"}}
  {{{t "mytheme" "Proudly published with {ghostLink}" ghostLink="<a href=\"https://ghost.org\">Ghost</a>"}}}
```
- and in .json translation files, for example for Spanish:
```
  "mytheme": {
      "Get the latest posts delivered right to your inbox": "Recibe los últimos artículos directamente en tu buzón",
      "Proudly published with {ghostLink}": "Publicado con {ghostLink}"
  }
```
- also added two very small stylesheet files, _assets/css/en.css_ and _assets/css/es.css_, for some css content strings that needed translation by override; stylesheets linked using Ghost's standard `getAssetUrl`
- see the complementary Ghost commit for additional details

### CODE REVIEW

**Comment by juan-g** [comment]
The complementary Ghost pull request is:

[i18n] Translatable Ghost's frontend: Themes, dates, pagination, subscribe forms
https://github.com/TryGhost/Ghost/pull/8437

**Comment by juan-g** [comment]
Added a minor commit to this pull request:

[i18n] Renamed new `{{i18nCss}}` css translation helper as `{{t_css}}`

pull request #306

- renamed new `{{i18nCss}}` css translation helper as more user friendly `{{t_css}}` for ease of use and consistency with the rest of helper names
- there is a complementary commit for Ghost's PR TryGhost/Ghost#8437

**Comment by juan-g** [comment]
[i18n] Separate .json translation files for themes

pull request #306

- for _.hbs_ templates in _content/themes_, using translation files: _content/themes/mytheme/assets/translations/mytheme_en.json_, _mytheme_es.json_, _mytheme_en-US.json_, etc. (replacing "_mytheme_" with the active theme, such as _casper_, etc.)
- more details in a complementary commit for Ghost's PR TryGhost/Ghost#8437

**Comment by juan-g** [comment]
[i18n] Moved _.css_ translation files for themes

pull request #306

- to facilitate translators' work, moved _.css_ translation files for themes from _assets/css/en.css_, etc. to _assets/translations/mytheme_en.css_, etc. (replacing "_mytheme_" with the active theme, such as _casper_, etc.)
- adjusted `{{t_css}}` helper and its test accordingly
- there is a complementary commit for Ghost's PR TryGhost/Ghost#8437

**Comment by juan-g** [comment]
[i18n] `(t)` translation helper's subexpressions for `{{plural}}` and other helpers

pull request #306

- using `(t)` translation helper's subexpressions inside `{{plural}}`, `{{subscribe_form}}`, and `{{input_email}}` helpers for placeholders, etc., instead of "`where`" parameters
- simplified these helpers; now similar to before the pull requests; just a few objects needed conversion to string for `{{plural}}`
- since `{{t}}` translation helper returns `new SafeString`, there is no need for `{{{t}}}` to preserve HTML; using now `{{t}}` instead in all cases
- adapted several templates for these changes
- subexpressions requested in pull request review
- there is a complementary commit for Ghost's PR TryGhost/Ghost#8437

**Comment by juan-g** [comment]
[i18n] `{{t_css}}` helper replaced by `{{theme}}` and `{{lang}}`

pull request #306

- adapted theme template _default.hbs_ for this change, including `<html lang="{{lang}}">`
- see more details in the two complementary commits for Ghost's PR TryGhost/Ghost#8437, and for gscan's PR TryGhost/gscan#48

**Comment by juan-g** [comment]
[i18n] minor improvements for translatability

pull request #306

- facilitating more the use of placeholders with subexpressions in full translation strings, rather than translating separate sentence fragments; often those fragments are in different order for different languages, therefore placeholders are better and more flexible
- when preserving HTML, back to using `{{{t}}}`; from now, this helper doesn't use a `SafeString` object which would prevent escaping, because often other helpers need that `(t)` returns a string to be able to work as subexpression
- because of this, the `{{plural}}` helper is again like before these pull requests, but with translations working
- examples:
  `{{tags prefix=(t "casper" " on ")}}`
  `{{{t "casper" "Read <a href='{url}'>more posts</a> by this author" url=(url)}}}`
- there is a complementary commit for Ghost's PR TryGhost/Ghost#8437

**Comment by juan-g** [comment]
[i18n] further usability improvement of translation helper

pull request #306

- now there is no need to include the theme name in `{{t}}`
  - before:
    `{{t "mytheme" "Subscribe"}}`
  - after:
    `{{t "Subscribe"}}`
- more details in the complementary commit for Ghost's PR TryGhost/Ghost#8437

**Comment by HLFH** [comment]
Hi. Will this be merged (are there some showstoppers) or shall we switch to https://github.com/juan-g/WorldCasper2?

**Comment by kirrg001** [comment]
> Hi. Will this be merged (are there some showstoppers) 

Won't be merged. Forgot to close.

> or shall we switch to https://github.com/juan-g/WorldCasper2?

👍

**Comment by HLFH** [comment]
Thank you @juan-g and @kirrg001 for this great work!
I added a PR for Isso support, French translation and Feedly fix on https://github.com/juan-g/WorldCasper2/pull/2.
Have a great evening!

**Comment by guillaume-sainthillier** [comment]
This work is awesome.
Could you explain me the reasons why this PR is not merged ?
I would be happy to make you a PR for at least call the "t" helper in the templates even if the translation files are not hosted directly in this repo.

**Comment by fr0der1c** [comment]
I wonder why this PR is not merged too. Translation is a built-in ability for Ghost, but the default theme doesn't support it. Wow.

**Comment by kevinansfield** [comment]
As mentioned in the [comment above](https://github.com/TryGhost/Casper/pull/306#issuecomment-359369023), if you want a translated theme you're free to use a fork such as https://github.com/juan-g/WorldCasper2 or any other theme and adapt it to your needs 😉 

Casper is intended as a minimal default theme that's useful for Ghost beginners to get started and customise to their needs. Adding localisation features which complicate/obscure the theme development for the large majority of users which don't have any localisation needs is counter to that focus.

**Comment by fr0der1c** [comment]
@kevinansfield 
> Adding localisation features which complicate/obscure the theme development
Will it complicate much?  I thought not hard-coding is a good thing.

**Pull request closed without merging**
