### PR TITLE
Display Subscribe button if Navigation Menu is not set

### PR DESCRIPTION
**Pull request by keiga-san**
Display 'Subscribe' button on every page if the 'Navigation Menu' is not set.

Class for standalone subscribe button is set to 'subscribe-button-standalone'. 
Button CSS style is taken from the previous version of theme.

subscribe_button

### CODE REVIEW

**Comment by keiga-san** [comment]
Add code for "Home" button. 

Now if Navigation Menu is not set, theme will look like it was in previous versions: with just "home" and "subscribe" buttons.

back_button

**Comment by nuclearpengy** [comment]
my two cents worth: If a user is already on the "home page" then I think the home button should be removed. Would need to clear this with @JohnONolan first though.

Take a look at how @JohnONolan's site looks, I think this is a good natural behaviour.

home page:

screen shot 2015-04-01 at 23 40 03

Post page:

screen shot 2015-04-01 at 23 41 01

**Comment by keiga-san** [comment]
@nuclearpengy Yes , you're right. I did so already. "Home" button appears only on: page, tag, author and post.

**Comment by nuclearpengy** [comment]
oh legend. that's awesome. thank you. made my evening. I'm going to go drink coffee and celebrate ;)

**Comment by NerosTie** [comment]
IMHO, the "HOME" button should be always here (except on the homepage), even if "menu" is set.
Just like before.

**Comment by keiga-san** [comment]
@NerosTie yes, thats right. Now "Home" button appears on the left if there are no logo is set.
On the right you can see "Subscribe" if there are no Menu, or "Menu" button if it set.

**Comment by NerosTie** [comment]
@keiga-san Cool! I hope it will be in the next update! :smile:

**Comment by MichielDeMey** [comment]
:+1: Care to solve the merge conflicts? :smile:

**Pull request closed without merging**
