### PR TITLE
Very small fix on author meta links color

### PR DESCRIPTION
**Pull request by lazyjazzie**
Small fix on author meta links.

### CODE REVIEW

**Comment by gargol** [comment]
Hey @lazyjazzie! Can you please include a screenshot comparing how it was before and after the fix? It's not clear _why_ this fix would be needed. Thaanks!

**Comment by lazyjazzie** [comment]
Sorry, It was some dark mode issue on author page's meta links color. I've reviewed css changes again and fixed this time properly.
Current dark mode visual is like this:

Screen Shot 2019-10-25 at 10 47 38

**Comment by lazyjazzie** [comment]
There is also some other color issues on light version
If author social meta links color set to dark grey color on light mode
`.author-social-link a {    
    color: var(--darkgrey);  
    font-weight: 600; 
}` 
Why there is something like this applies? It renders like this on my website
`.site-header-background {  
    color: #fff;  
}`

Screen Shot 2019-10-25 at 11 03 03

**Comment by peterzimon** [comment]
Hey @lazyjazzie ,
Thanks a lot for spotting these bugs, the links in the author header definitely are not supposed to look/work like that. I appreciate your contribution, your proposed fix however doesn't consider all the edge cases. If you could allow maintainers to edit your casper master repo then I can push my changes to that and merge your PR back to master.
Thanks

PS: it's a conscious design decision to use white text and link colors over background images as for most of the backgrounds that works the best.

**Comment by lazyjazzie** [comment]
@peterzimon  Hey, thanks for replying.
Yeah I agree with you on that all the edge cases thing :), I'll try to fix on every case ASAP.

**Comment by peterzimon** [comment]
Hey @lazyjazzie ,
Actually I already have those fixes locally so you/we don't need to do double work. All you need to do is just allow maintainers to edit this PR and I can push it 🙂(You can do this by checking the checkbox in the right sidebar on this page.) 
Screenshot 2019-10-30 at 9 29 50
Thanks again

**Comment by lazyjazzie** [comment]
@peterzimon 
Hey, done

**Comment by peterzimon** [comment]
Hey @lazyjazzie,
Eventually I created a different PR (https://github.com/TryGhost/Casper/pull/642), cherry-picked your commit and pushed all the changes to Casper master 🙂 . Unfortunately I couldn't push to this (original) PR because it was from your master branch. Next time I would suggest to create a branch for your PRs. Thanks again for your contribution.

**Pull request closed without merging**
