### PR TITLE
Fix  match the @custom.navigation_layout in default.hbs

### PR DESCRIPTION
**Pull request by officialrajdeepsingh**
Fix the issue of match the @custom.navigation_layout in the `default.hbs` file.

### CODE REVIEW

**Comment by minimaluminium** [comment]
Hi @officialrajdeepsingh, `^` instead of `#` is used for negating the helpers, and was used in these places intentionally. For example, it's telling that show a search icon when the navigation layout is _not_ "Stacked", or show a lock icon when a post is _not_ public.

**Comment by officialrajdeepsingh** [comment]
I can't understand; please provide docs related to `^` on how we can use it with ghost theme development.

**Comment by minimaluminium** [comment]
https://ghost.org/docs/themes/helpers/is/

For example, you can find how `^` is used with `is` helper on the bottom of the page.

**Comment by officialrajdeepsingh** [comment]
Now I understand. Thank

**Pull request closed without merging**
