### PR TITLE
Improvement to .post-content .full-img

### PR DESCRIPTION
**Pull request by mankittens**
New code will center images and allow them to extend beyond the main text column, but not force them to be as wide as the maximum allowed width.

### CODE REVIEW

**Comment by mankittens** [comment]
Just realized. This needs a small fix for mobile width. Don't accept it.

**Comment by JohnONolan** [comment]
Can you explain what problem you're trying to solve with this change?

**Comment by mankittens** [comment]
It's minor, admittedly, but essentially, it will cap the width at 126% of .full-img images but not force .full-img images *to be* 126%.

**Comment by JohnONolan** [comment]
The current implementation only forces images to 126% if they are of sufficient resolution to go to that size. If they aren't they already stay centered at their original resolution.

**Comment by mankittens** [comment]
Under the current rules, any image greater than 100% and less than 126% is stretched to 126%.

**Comment by novaugust** [comment]
> Under the current rules, any image greater than 100% and less than 126% is stretched to 126%.

It's true

This works well for me, I'm using it over on my blog. 
The transform + relative positioning bit is a stroke of genius, I've been wondering for weeks how I could pop images out to the fullscreen when they're wrapped in centered 700px `<p>`s

**Comment by novaugust** [comment]
@mankittens did you check your changes on a smaller screen? There's a second `.full-img` rule that plays with image width on the small screen MQ

**Comment by mankittens** [comment]
I did notice that after my first commit. I went ahead and removed the `margin: 0 -16%` in the `@media max-width: 500` section, since images auto-center at any width with this fix.

You know, I just realized that these changes obsolete the need for a .full-img tag, no? (This would cut out some JavaScript in index.js!) I'll double-check in a bit.

**Comment by mankittens** [comment]
Was able to cut out all references to .full-img, in index.js and style.css, since the new css rules are happy to center images big and small. Working example here: https://apatchofcode.com/cant-sign-out-of-icloud-account/.

**Comment by JohnONolan** [comment]
I wasn't convinced by this initially - but you've done a really good job of demonstrating why this is a good change :+1: - If you can squash and rebase, I'd be happy to merge!

**Comment by novaugust** [comment]
No more js jumping! Nice work =) Just in case you aren't sure what he means by squashing, [here's a little snippet](https://github.com/TryGhost/Ghost/wiki/Git-workflow#clean-up-history) from the Ghost contributing guide.

And i have to leave this somewhere: these changes + setting max-width to 100vw is fun.

**Comment by mankittens** [comment]
Got it! Thanks for pointing me to the Ghost docs.

**Comment by mankittens** [comment]
This is ready to merge!

**Comment by mankittens** [comment]
Committed with smartresize and debounce removed.

**Comment by JohnONolan** [comment]
Great work :+1:

**Pull request merged**
