### PR TITLE
fix DISQUS iframe margin problem

### PR DESCRIPTION
**Pull request by Rezaaa**
on post template, DISQUS iframe have some margin and it's out of screen.

### CODE REVIEW

**Comment by JohnONolan** [comment]
Thanks for getting involved! Please could you provide a before/after screenshot of this problem and what the PR fixes?

**Comment by Rezaaa** [comment]
@JohnONolan 
screenshot

**Comment by JohnONolan** [comment]
The bug is valid - but that's not the right fix. That's overriding the iframe default margin on all iframes, which is not what we want. We'll need to find a way to target the disqus iframe specifically, or modify the default iframe style to be applied only to content and not elsewhere.

**Comment by Rezaaa** [comment]
@JohnONolan check it again please.

**Comment by JohnONolan** [comment]
This is fine - but it needs to be squashed down to 1 commit and the code needs to live in the "3rd party" section - same place where we have the custom styles for Github Gists

**Comment by mankittens** [comment]
This fix should specifically target the #dsq-5 iframe. It's not an issue for all disqus iframes, as the current commit reflects.

```css
/* Disqus */
iframe#dsq-5 {
    margin: 0;
}
```

This should be sufficient, plus or minus `iframe`.

**Comment by mankittens** [comment]
The `.post-template >` selector is a bit overqualified, imo.

**Comment by Pherserk** [comment]
dsq-5 id could change, depending on third parties.
In my opinion is better avoiding any style directive that addresses directly the iframe tag.

**Comment by JohnONolan** [comment]
@Rezaaa feel free to re-open if you have time to update

**Pull request closed without merging**
