### PR TITLE
Disable horizontal scrollbar in post page

### PR DESCRIPTION
**Pull request by minwe**

### CODE REVIEW

**Comment by hkalant** [comment]
This horizontal scrollbar appeared in the latest version of Casper (1.2.2) after upgrading to Ghost 0.6.2 for. But if you open and then close the navigation for example, the horizontal scrollbar disappears.

**Comment by Minwe** [comment]
Yes, I upgraded to Ghost v0.6.2 and the horizontal scrollbar appears.

So  I add the style to my Ghost blog to resolve this problem.

**Comment by JohnONolan** [comment]
Could you provide some more details about what browser, OS, etc this is appearing in please? It's hard to help you without the details

**Comment by Minwe** [comment]
@JoeBonham 

The UA:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
```

See more details on the screenshot below:

aa

**Comment by rajeevedmonds** [comment]
Confirming same result on my Win 8.1 machine.

UA : `Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0`

**Comment by dvrylc** [comment]
Same bug here - Casper 1.2.4, Ghost 0.6.4. 

UA: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2414.0 Safari/537.36`

**Comment by f-plante** [comment]
Same bug :
Casper 1.2.3
My UA :
`Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:38.0) Gecko/20100101 Firefox/38.0`

**Pull request closed without merging**
